// client/src/pages/initial.page.vue
<script setup lang="ts">
import { getChat, getMe, joinMe } from "@/api/api";
import { useMiniApp } from "vue-tg";
import { useRouter } from "vue-router";
import { onMounted } from "vue";
import axios from "axios";
import { useUserStore } from "@/stores/user.store";
const miniApp = useMiniApp();
const initData = miniApp.initData;
const router = useRouter();
const startData = miniApp.initDataUnsafe.start_param || "";
onMounted(async () => {
  console.log(miniApp.initData);
  const userData = await getMe(initData);
  console.log(startData, startData.length);
  if (userData !== null) {
    if (miniApp.initDataUnsafe.start_param !== undefined) {
      const getChatResponse = await getChat(initData, startData);
      if (getChatResponse) {
        router.replace(`/chats`);
        setTimeout(() => {
          router.push(`/chat/${startData}`);
        }, 100);
      } else {
        router.replace("/invite");
      }
    } else {
      router.replace("/chats");
    }
  } else {
    router.replace("/about/1");
  }
});
</script>
<template></template>

// client/src/pages/initial.page.tsx
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import useInitDataStore from "../stores/InitData.store";

const InitialPage = () => {
  const { initDataStartParam: startParam, initData } = useInitDataStore();
  const navigate = useNavigate();
  console.log(initData);
  useEffect(() => {
    if (
      startParam !== undefined &&
      startParam !== null &&
      startParam.length > 0
    ) {
      navigate("/chats", { replace: true });
      navigate(`/chat/${startParam}`);
    } else {
      navigate("/chats", { replace: true });
    }
  }, []);
  return null;
};

export default InitialPage;
