// client/src/pages/profile.page.tsx
import { initData, openTelegramLink } from "@telegram-apps/sdk-react";
import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { getUserById } from "../api/api";
import EBBComponent from "../components/enableBackButtonComponent";
import InfoBlockComponent from "../components/infoBlock.component";
import InfoParagraphComponent from "../components/infoParagraph.component";
import { UserData } from "../types/user.interface";
import { handleImageError } from "../utils/imageErrorHandler";
import DevImage from "../assets/dev.png";
import ButtonComponent from "../components/button.component";
import TGWhite from "../assets/tg_white.svg";
const ProfilePage = () => {
  const { userId } = useParams();
  const [userData, setUserData] = useState<UserData>();

  const fetchProfileData = async () => {
    const data = await getUserById(initData.raw() ?? "", userId ?? "");
    if (data) {
      setUserData(data);
    }
  };

  useEffect(() => {
    fetchProfileData();
  }, []);

  return (
    <EBBComponent>
      <div className="w-[95%] mx-auto py-4 px-4 overflow-y-auto h-[120vh]">
        <div className="flex flex-col items-center gap-[17px]">
          <img
            className="w-[115px] h-[115px] rounded-full object-cover"
            src={userData?.avatar || DevImage}
            onError={handleImageError}
          />

          <div className="text-center">
            <p className="font-semibold inline-flex text-[20px] gap-[10px] items-center">
              {userData?.firstName} {userData?.lastName}
            </p>
            <p className="text-hint text-[15px]">
              {`@${userData?.telegramUsername}`}
            </p>
          </div>
          <ButtonComponent
            content={
              <>
                Написать <img src={TGWhite} />
              </>
            }
            handleClick={() => {
              openTelegramLink(`https://t.me/${userData?.telegramUsername}`);
            }}
            state={"active"}
          />
        </div>
        <div className="rounded-lg mt-[15px] mx-auto">
          <InfoBlockComponent>
            <InfoParagraphComponent
              title="Место работы"
              content={userData?.company ?? ""}
            />
            <InfoParagraphComponent
              title="Должность"
              content={userData?.role ?? ""}
            />
          </InfoBlockComponent>
          <div className="px-[16px] text-hint mb-[8px] mt-[15px] text-[13px]">
            ПОДРОБНЕЕ
          </div>
          <InfoBlockComponent>
            <InfoParagraphComponent
              title="Описание"
              content={userData?.bio ?? ""}
            />
          </InfoBlockComponent>
        </div>
      </div>
    </EBBComponent>
  );
};

export default ProfilePage;

// client/src/pages/profile.page.vue
<script setup lang="ts">
// WE NEEEED A HUUUUUGE REFACTOR IN HERE

import { onMounted } from "vue";
import { useRouter, useRoute } from "vue-router";
import { useProfileStore } from "@/stores/profile.store";
import Button from "@/components/button.vue";
import { useMiniApp } from "vue-tg";
import { getMe } from "@/api/api";
const router = useRouter();
const profileStore = useProfileStore();
const avatar = useMiniApp().initDataUnsafe.user?.photo_url;
const initData = useMiniApp().initData;
const goToChats = () => {
  router.push("/chats");
};

const tgUsername = useMiniApp().initDataUnsafe.user?.username;

onMounted(async () => {
  const route = useRoute();
  const userId = route.params.userid;
  const myInfo = await getMe(initData);
  console.log(myInfo);
  if (route.params.userid === undefined) {
    profileStore.setProfile({
      firstName: myInfo.firstName,
      lastName: myInfo.lastName,
      role: myInfo.role,
      bio: myInfo.bio,
      company: myInfo.company,
      avatar: myInfo.avatar,
    });
  } else if (userId === myInfo.telegramId) {
    router.back();
    router.push("/profile");
  }
});
</script>

<template>
  <div class="w-full flex flex-col h-full items-center p-4">
    <div class="w-full" v-if="!profileStore.editMode">
      <div class="flex flex-col items-center">
        <img
          class="w-28 h-28 rounded-full object-cover"
          :src="`https://${profileStore.profile.avatar}`"
          alt="User Avatar"
        />
        <div class="flex flex-row items-center gap-[10px] mt-[17px]">
          <p class="font-semibold text-[20px text-center">
            {{ profileStore.profile.firstName }} {{ profileStore.profile.lastName }}
          </p>
          <img
            src="/src/assets/edit_24.svg"
            alt=""
            srcset=""
            @click="
              () => {
                profileStore.toggleEditMode;
                router.push('/profile/edit');
              }
            "
          />
        </div>
        <p class="text-gray-500">{{ `@${tgUsername}` }}</p>
      </div>

      <Button class="flex flex-row mt-[10px] items-center gap-[6px] m-auto">
        Написать <img class="w-4 h-4" src="/src/assets/tg_white.svg" alt="Telegram" />
      </Button>

      <div class="mt-6 p-4 rounded-lg">
        <h2 class="text-sm px-[16px] font-semibold mb-2">ABOUT</h2>
        <div class="bg-form px-[16px] rounded-[12px]">
          <div class="border-b py-[12px] border-tint">
            <p class="text-xs text-hint">Место работы</p>
            <p class="">{{ profileStore.profile.company }}</p>
          </div>

          <div class="py-[12px] border-b border-tint">
            <p class="text-xs text-hint">Должность</p>
            <p class="whitespace-pre-line">{{ profileStore.profile.role }}</p>
          </div>

          <div class="py-2">
            <p class="text-xs text-hint">Описание</p>
            <p class="text-sm whitespace-pre-line">
              {{ profileStore.profile.bio }}
            </p>
          </div>
        </div>
      </div>
    </div>

    <Button @click="goToChats">GOTO CHATS</Button>
  </div>
</template>

<style scoped>
fieldset {
  border-radius: 12px;
  margin: 0;
  padding: 0;
}
legend {
  margin-left: 12px;
  padding: 0 4px;
}
</style>
